version: "2"
volumes:
  mongodata:
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodata:/data/db
    container_name: mongodb
    command: --wiredTigerCacheSizeGB 2
    mem_limit: 2g
    
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - 127.0.0.1:6379:6379

  ppengo:
    build: "ppengo"
    container_name: ppengo
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_DATABASE=mongodb://mongodb/wgeteer
      - REDIS_URL=redis://cache
      - TZ=Asia/Tokyo
    tty: true
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./ppengo/public:/home/node/public
      - ./ppengo/routes:/home/node/routes
      - ./wgeteer/routes/models:/home/node/routes/models
      - ./ppengo/views:/home/node/views
      - ./ppengo/bin:/home/node/bin
    command: npm start
    #command: /bin/sh

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    links:
      - mongodb
    depends_on:
      - mongodb
    container_name: mongo-express