version: "3"
volumes:
  mongodata:
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodata:/data/db
    container_name: mongodb

  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - 127.0.0.1:6379:6379

  ppengo:
    build: "ppengo"
    container_name: ppengo_alpine
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_DATABASE=mongodb://mongodb/wgeteer
      - REDIS_URL=redis://cache
      - TZ=Asia/Tokyo
    tty: true
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./ppengo/public:/var/www/app/public
      - ./ppengo/routes:/var/www/app/routes
      - ./ppengo/views:/var/www/app/views
      - ./ppengo/bin:/var/www/app/bin
    #command: npm start
    command: /bin/sh
