services:
  wgeteer:
    build: .
    environment:
      - NODE_ENV=development
      - VTKEY
      - GSBKEY
      - PPENGO
      - X11VNC_PASSWORD="password"
      - DISPLAY=:99
    tty: true
    init: true
    container_name: wgeteer
    volumes:
      - node_modules:/home/node/node_modules
      - ./routes:/home/node/routes
      - ./IP2LOCATION-LITE-DB1.IPV6.BIN:/tmp/IP2LOCATION-LITE-DB1.IPV6.BIN
      - ./entrypoint.sh:/home/node/entrypoint.sh
      - ./package.json:/home/node/package.json
      - ./ecosystem.config.js:/home/node/ecosystem.config.js
      - ./tmp:/tmp
      - ./webappanalyzer:/home/node/webappanalyzer
    network_mode: "host"
    ports:
      - 127.0.0.1:5900:5900
    #working_dir: /home/node/app
    #command: dumb-init -- node --inspect --optimize_for_size --gc_interval=100 --max-old-space-size=1024 agenda
    #command: node --inspect --optimize_for_size --gc_interval=100 --max-old-space-size=1024 agenda
    command: /bin/bash /home/node/entrypoint.sh
    mem_limit: 2g
    #restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  gosb:
    build: "gosb"
    tty: true
    container_name: gosb
    volumes:
      - ./gosb:/tmp/gosb
    ports:
      - 127.0.0.1:3001:3001
    working_dir: /app
    command: ./bin/sbserver -db "/tmp/gosb/gsbv4.db" -srvaddr "0.0.0.0:3001" -apikey ${GSBKEY}
    mem_limit: 1g

volumes:
  node_modules:
