version: "2"
services:
  wgeteer:
    build: .
    environment:
      - NODE_ENV=development
      - VTKEY
    tty: true
    container_name: wgeteer
    volumes:
      - ./routes:/home/node/app
    network_mode: "host"
    working_dir: /home/node/app
    #command: /bin/sh
    command: dumb-init -- node --optimize_for_size --gc_interval=100 --max-old-space-size=2048 scheduler
    mem_limit: 2g
    restart: always

  gosb:
    build: "gosb"
    tty: true
    container_name: gosb
    volumes:
      - ./gosb:/tmp/gosb
    ports:
      - 127.0.0.1:3001:3001
    working_dir: /app
    command: ./bin/sbserver -db "/tmp/gosb/gsbv4.db" -srvaddr "0.0.0.0:3001" -apikey ${GSBKEY}
