services:
  wgeteer:
    build: .
    environment:
      #- NODE_ENV=development
      - VTKEY
      - GSBKEY
      - PPENGO
      - X11VNC_PASSWORD="password"
      - DISPLAY=:99
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
    tty: true
    init: true
    container_name: wgeteer
    volumes:
      - ./app:/home/node/app
      - ../data/npm/cache:/home/node/.npm
      - ../data/npm/wgeteer:/home/node/app/node_modules
      - ../data/webappanalyzer:/home/node/webappanalyzer
      - ../data/IP2LOCATION-LITE-DB1.IPV6.BIN:/tmp/IP2LOCATION-LITE-DB1.IPV6.BIN
    network_mode: "host"
    ports:
      - 127.0.0.1:5900:5900
    working_dir: /home/node/app
    command: /bin/bash /home/node/app/entrypoint.sh
    mem_limit: 2g
    #restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  gosb:
    build: "gosb"
    tty: true
    container_name: gosb
    volumes:
      - ./gosb:/tmp/gosb
    ports:
      - 127.0.0.1:3001:3001
    working_dir: /app
    command: ./bin/sbserver -db "/tmp/gosb/gsbv4.db" -srvaddr "0.0.0.0:3001" -apikey ${GSBKEY}
    mem_limit: 1g

