version: "3"
services:
  wgeteer:
    build: .
    environment:
      - NODE_ENV=development
    tty: true
    container_name: wgeteer
    volumes:
      - ./routes:/home/node/app
    network_mode: "host"
    working_dir: /home/node/app
    #command: /bin/sh
    command: node worker
